# Source language and JDK version to use
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties
install: gradle setupCIWorkspace
script: gradle build -PbuildNumber=$TRAVIS_BUILD_NUMBER -PciSystem=travis -Pcommit=${TRAVIS_COMMIT:0:7}

# Perform steps after compilation/test success
after_success:
  # Check if commit s not a pull request, if git repo is official, and if branch is master. If checks pass, add libs and deploy artifacts to Maven repository.
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == Ordinastie/MalisisCore ]] && [[ $TRAVIS_BRANCH == master ]] && gradle uploadArchives"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Super secure, encrypted variables! Ssssh!
    - secure: eLRcYXZuIG57lRbCtCIVw9nvLYntFyt6sTSJtjHWD1qa8xaJScHVvBBMZ2iga6KnFwgALNkhCqXpjVzabY0okr2ehf0XhIIQbD91ei2xY/d3WuivtkrD1ECjOaDQCnLMBsNJ/jfydV0vRePXaSL/f/5nZY7xa5evrPpEjhBn36U=
    - secure: 1e3AVn9sskiWTbM8lJC94dIc2DHq/a/AM+5JGYF0CMmlFLeCkSqPhIaBylPAf1DvbAATY/PIhRGIswiOopBtuGnyZSJRPsLEdcD/bz9lHaVZQZoYuxvR/otWWuI3Y9An0GK4jCHMj0+EaJEb3LtdOHUapmezmiIgl/lOufty7YQ=
